# Generated by Django 5.2.6 on 2025-10-08 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
